### 프로젝트 내 전체 마일스톤 조회
GET /milestones/projects/1
Host: localhost:8080
Content-Type: application/json

### 특정 마일스톤 조회
GET /milestones/1
Host: localhost:8080
Content-Type: application/json

### 프로젝트 내 마일스톤 생성
POST /milestones/projects/1
Host: localhost:8080
Content-Type: application/json

{
  "name" : "마일스톤 만들기",
  "startPeriod" : null,
  "endPeriod" : null,
  "status" : "진행"
}

### 마일스톤 수정
PUT /milestones/1
Host: localhost:8080
Content-Type: application/json

{
  "name" : "마일스톤 수정",
  "startPeriod" : null,
  "endPeriod" : null,
  "status" : "종료"
}

### 마일스톤 삭제
DELETE /milestones/2
Host: localhost:8080
Content-Type: application/json