### 프로젝트 상태 목록 정보 조회
GET /project-status
Host: localhost:9091


### 프로젝트 상태 단건 정보 조회1
GET /project-status/1
Host: localhost:9091


### 프로젝트 상태 단건 정보 조회2
GET /project-status/2
Host: localhost:9091


### 프로젝트 상태 단건 정보 조회3
GET /project-status/3
Host: localhost:9091


### 프로젝트 상태 단건 정보 조회4
GET /project-status/4
Host: localhost:9091


### 프로젝트 상태 정보 생성
POST /project-status
Host: localhost:9091
Content-Type: application/json

{
  "name" : "name4"
}

### 프로젝트 상태 정보 수정
PUT /project-status/4
Host: localhost:9091
Content-Type: application/json

{
  "name" : "updated Id"
}

### 프로젝트 상태 정보 삭제
DELETE /project-status/8
Host: localhost:9091